version: "3"
services:
        app:
                build: ./app/
                tty: true
                ports:
                        - "8000:8000"
                volumes:
                        -  ./app:/go/src/app
                container_name: app-container
                depends_on:
                        -  db

        db:
                image: mysql:5.7
                volumes:
                        -  ./db/init:/docker-entrypoint-initdb.d
                environment:
                        -  MYSQL_ROOT_PASSWORD=8jjStzw7
                ports:
                        -  "3306:3306"
                container_name: mysql-container
